### ISSUE TITLE
Release NuGet

### ISSUE THREAD

**Issue by agnauck** [MichaCo/DnsClient.NET#1]
do you have plans to publish a release NuGet soon?
I have done some testing with SRV and TXT lookups and it works great

**Comment by MichaCo** [comment]
Yup. I need to find some time to clean up some things and maybe implement some new stuff. But yes, should be fine for a first release pretty soon

**Comment by MichaCo** [comment]
@agnauck first version is now released, let me know what you think and if there are any suggestions
