### ISSUE TITLE
Out of size exception

### ISSUE THREAD

**Issue by RufusJWB** [MichaCo/DnsClient.NET#10]
If I try to query the CAA records for the site `big.basic.caatestsuite.com`, I receive an ArgumentOutOfRangeException, regardless if I run it locally or if I run it on http://dnsclient.michaco.net/ . This site has 1001 CAA records. Do you have an idea, where I can increase the maximum size?

**Comment by MichaCo** [comment]
Well that looks like a bug in the TCP retrieval. I'll take a look

**Comment by MichaCo** [comment]
I've tested my changed with your CAA test server thing, seems to work.
If you want, give it a try with the latest beta bits
https://www.myget.org/feed/dnsclient/package/nuget/DnsClient

**Comment by RufusJWB** [comment]
I can confirm that it is working. Most interestingly, it doesn't work, if I run it against my local DNS server but it works, if I run it against google DNS.
