### ISSUE TITLE
Severe Socket leak

### ISSUE THREAD

**Issue by smasherprog** [MichaCo/DnsClient.NET#106]
I believe there is another leak with connections in the dnsclient. 
I posted about a previous leak that I found before and I think it might be here again in a different form. 
https://github.com/MichaCo/DnsClient.NET/issues/67

Same setup as before where we use this dnsclient library through the MongoDB.Driver v 2.11.6

This time, there is not a memory leak, but a tcp socket exhaustion leak where all available sockets on the machine are consumed and never released. The problem is very obvious and severe. I tested reverting back to 1.3.2 and the problem immediately went away. 

Unfortunately, I cannot get a memory dump of our servers because all available sockets on the server are consumed within a few minutes and I no connections in or out  are available. So, I have to reboot them to get access (Virtual Servers).

I will try to get more info, but this is all I have for now. But the latest version does have a serious serious bug..

**Comment by MichaCo** [comment]
If you'd have a way for me to reproduce it, that would be great. Or any hints to look for really ^^

I did some simple testing, even creating a new client instance in a loop, on windows and Linux, and cannot really find anything which would hint to a memory leak, memory is just stable all the time.

If you can really reproduce it that easily with the new version vs the old version then it must be some specific setting or configuration I guess

**Comment by smasherprog** [comment]
Ill try to get more info.
I named the ticket incorrectly initially, this is not a memory leak, but a socket leak. 
Sockets are not being freed ever.

**Comment by smasherprog** [comment]
I think this might  be an issue with our code. The mongo library has some subscribers which I think I am using in an incorrect way which is causing a circular reference therefore they cannot be garbage collected.

I am making more changes and reviewing the effects.

**Comment by smasherprog** [comment]
Im leaning more towards a mongo library bug with their internal caching of connections. I believe that I was wrong assuming it was in this library. I am going to close this for now and let you know what I find.
