### ISSUE TITLE
Honeypot alarm/alerts

### ISSUE THREAD

**Issue by weedkiller** [MichaCo/DnsClient.NET#107]
Hello I wanted to share some information on Honeypot https://github.com/topics/honeypot that have a list of bad IP's threats.

Is there a way to integrate that list check here as an option at startup, so we know some of those are from the honey pot list, to allow the application to ignore/blacklist those requests

**Comment by MichaCo** [comment]
I'm not convinced it would be a good fit to build add that here. This should be just a relatively simple DNS library ;)

You can implement that into your own application or build something on top of this library which has a black or whitelist or something I guess.
You can always just compare the domain names returned from a DNS query against some list
