### ISSUE TITLE
Additionals count in Header

### ISSUE THREAD

**Issue by isaeed** [MichaCo/DnsClient.NET#11]
hi, it seems that Additionals count in header is wrong. its always 1+ then actual count. please have a look, and any idea how to correct it. thanks

**Comment by MichaCo** [comment]
I'm always requesting the size record right now, that's why there is always one optional record which is hidden.

**Comment by isaeed** [comment]
actually it is misleading when you get 1 in header but 0 ( zero ) in response actual count.
