### ISSUE TITLE
TaskStatus Failed

### ISSUE THREAD

**Issue by rjs5327** [MichaCo/DnsClient.NET#15]
Hi, Im getting a Task status failed. If i don't check it with the if statement it will crash the program. I have System.Buffers 4.01 which is  all that is called for with framework 4.5 or greater. So what gets me is this use to work and all a sudden it didn't anymore. My guess is there is more requirements than Buffers. If so can we update the notes to show what is needed. Im thinking of putting the source code in the project to debug it. But im not sure that is the issue since it has to do with the Threading.

using System;
using System.Linq;
using DnsClient;

namespace WEA_Resources
{
    class EmailChecker
    {
        public bool EmailOK(string email)
        {
            // Does a DNS lookup to check if anything exsist out there.

            string output = email.Substring(email.IndexOf('@') + 1);
            var lookup = new LookupClient();
            var result = lookup.QueryAsync(output, QueryType.ANY, QueryClass.IN);
            if (result.Status != System.Threading.Tasks.TaskStatus.Faulted)
            {
                var mx_count = result.Result.AllRecords.MxRecords().Count();    // Mail Exchanges
                var A_count = result.Result.AllRecords.ARecords().Count();      //IPv4 Addresses
                var Aaaa_count = result.Result.AllRecords.AaaaRecords().Count();//Ipv6 Addresses

                if (mx_count > 0)
                {
                    return true;
                }
                else
                {
                    System.Windows.MessageBox.Show("No MX Records found for that email address!" + Environment.NewLine + "Please Double check that email!", "Invalid Email!", System.Windows.MessageBoxButton.OK, System.Windows.MessageBoxImage.Warning);
                    return false;
                }
            }
            else
            {
                System.Windows.MessageBox.Show("MX Records Checker Faulted!" + Environment.NewLine + "Fait of Emil Questionable!", "Error!", System.Windows.MessageBoxButton.OK, System.Windows.MessageBoxImage.Warning);
                return true;
            }
        }        
    }
}

**Comment by MichaCo** [comment]
Either don't use the async methods or implement async/await correctly. You are lacking an await, that's why the task might not be completed right after `lookup.QueryAsync` is invoked.

either `await lookup.QueryAsync` or use the synchronous method instead (as your `EmailOk` method isn't async either.
