### ISSUE TITLE
Problematic reference to Microsoft.Win32.Registry, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

### ISSUE THREAD

**Issue by georgschausberger** [MichaCo/DnsClient.NET#154]
version 1.6.0 is referencing the following dependencies which are not provided by older .NET Core frameworks this leads to TypeLoadExceptions in special cases

**Comment by MichaCo** [comment]
Not sure what you mean by `older .NET Core frameworks`, Any example? The package is compatible with netstandard 1.3 and 2, so there shouldn't be any problems with any current .NET Core which is in LTS

There is an issue on windows platforms which are not really windows... where the library doesn't work. That's tract in another bug already, see #149

**Comment by georgschausberger** [comment]
Thanks @MichaCo The issue was caused by custom assembly load context implementations on our plugin based application. Therefore I think it's not relevant any more. Thanks for having a look.
