### ISSUE TITLE
Behavoir on iOS

### ISSUE THREAD

**Issue by vbisbest** [MichaCo/DnsClient.NET#16]
Seems that getting name servers is strange on iOS (iPhone 6 on wifi).   Making this call to retrieve name servers:
var nameServers = NameServer.ResolveNameServers(false, true);

returns:
2001:4860:4860::8844
2001:4860:4860::8888
8.8.4.4
8.8.8.8

First of all the parameter for ipv6 is set to false but it appears it was returned anyways.  Secondly, it only pulled back good dns servers rather than the real DNS server.  I think this is a limitation on iOS but I just want to confirm.  On Android the real DNS server is returns and google DNS servers are not included.

Thanks
Ray

**Comment by MichaCo** [comment]
Hey @vbisbest, you set the second parameter, fallbackToGooglePublicDns = true. This means, if anything goes wrong in the name server retrieval and you'd get 0, the call at least returns the google public DNS servers.

Looks like the call just doesn't work on iOS, probably some limitation in the low level APIs. I have native calls for Linux and Windows with fallbacks, but don't know if there is any implementation in .NET core for iOS, highly doubt that'll work ;)

**Comment by vbisbest** [comment]
Thanks for your answer!  There is a low level call to get the DNS address and I am trying to work on that now.  I use low level calls now for SRV records.  Just need to figure out this other call.  Will post here once I get it and perhaps you can add it to your library so its all embedded.

**Comment by MichaCo** [comment]
I guess you are using Xamarin right? Can you check if 
[NetworkInterface.GetAllNetworkInterfaces]( https://developer.xamarin.com/api/member/System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces/) returns anything?

**Comment by vbisbest** [comment]
I am using Xamarin and it does not return anything.  It really is locked down.

**Comment by vbisbest** [comment]
well I kind of have it working.  I able able to pull the DNS server address via a libresolv dll call.  However after the function exits, I get a nullref exception and I dont know why.  Do you have experience with marshaling calls?

**Comment by vbisbest** [comment]
I have this working.  Do you want to try to add this to your project?

**Comment by MichaCo** [comment]
Great! :>
If you could create a simple example project and put it into a public github repo, I can check it out, sure.
My problem is, I don't really have any iOS devices, so it might get a little bit tricky to test ^^

**Comment by vbisbest** [comment]
well yes because it does not work in the simulator, only on real device.   I will get it posted.  Also 2 more items.

1. Do the DNS servers go in order?  i.e.  1st server is checked, it fails, then goes to the 2nd server?  I want to be sure that the device DNS server is check first before moving to GoogleDNS.
2. It would be great if you could add the DNS server used to the AuditTrail output.

Thanks.

**Comment by MichaCo** [comment]
The used server should be in the audit trail

```
;; SERVER: 8.8.4.4#53
```

Regarding your 1st question, yeah kind of. It should always go through the list in order unless one server totally fails and gets disabled, then that server will be out of rotation until no servers are left
