### ISSUE TITLE
Star CNAME lookup

### ISSUE THREAD

**Issue by Seifert69** [MichaCo/DnsClient.NET#170]
I have a domain with a "star" CNAME record, like this:

*.id.pub CNAME alias.somewhereonamazon.com

This code returns null when I query:

            var lookup = new LookupClient();
            var result = lookup.Query("something.id.pub", QueryType.CNAME);
            var record = result.Answers.CnameRecords().FirstOrDefault();

It also returns null if I try to query with "*.id.pub" ...

Or I might have done something wrong. 

What's the expected behaviour?

**Comment by MichaCo** [comment]
Not sure if that has anything todo with this client/library. 
The DNS server has to support that query. I know that not all webhost providers support that for example.

Did you try any other DNS resolver?  nslookup or dig?

**Comment by Seifert69** [comment]
With this workaround I can retrieve the CNAME:

```
           var lookup = new LookupClient();
            var result = lookup.Query(inputHostName, QueryType.SRV);

            var srvRecord = result
                .Answers.OfType<CNameRecord>()
                .FirstOrDefault();
            if (srvRecord == null)
                return null;
            return srvRecord.CanonicalName;
```

Give that I can get it there, I would say that the behavior of the previous code I posted seems unexpected. I guess I would have expected that either anything fitting the wildcard, or the wildcard domain, would return the CName.

Maybe I wrote the first bit of code incorrectly.

**Comment by MichaCo** [comment]
well the CNAME record isn't defined for `something.id.pub` right? It is only defined on the root I guess.
That's probably why the query for CNAME on the full domain doesn't return anything.
That's why I asked if you tried that query with any other resolver, if those also don't give you any CNAME records for the same query, this library will not either.
DnsClient will just give you whatever your DNS server returns.

**Comment by Seifert69** [comment]
The CNAME looks like this:

*.id.pub CNAME somedomain.com.

So www.id.pub will CNAME to somedomain.com. I can type anything, abracadabra.id.pub and it will CNAME to somedomain.com. The DNS server does return it correctly. So it's likely something in your CnameRecords() that can't interpret it correctly.

**Comment by MichaCo** [comment]
this works just fine for me
```
static void Main(string[] args)
{
    var client = new LookupClient(NameServer.GooglePublicDns);
    var result = client.Query("something.id.pub", QueryType.CNAME);

    Console.WriteLine(result.Answers.CnameRecords().First());
}
```

**Comment by MichaCo** [comment]
@Seifert69 your initial code without specifying to use Google Public DNS works for me, too.
It most likely depends on what DNS server you have configured / use and if those records are available on that server.

Again, DNS Client can just give you the data the server returns for a query.

**Comment by Seifert69** [comment]
You're right. It works now. Totally weird. I spent hours trying to make it work. I've probably done something really stupid without realizing it.  Well at least the code was right :-) Sorry for wasting your time. At least now something will pop up on Google if people search for c# CNAME wildcard lookup (was very sparse).

Thanks for your help 🥇
