### ISSUE TITLE
Trailing `.` in MxRecord.DomainName.Value

### ISSUE THREAD

**Issue by bstordrup** [MichaCo/DnsClient.NET#190]
If I make a query for MX records providing a host name `somedonain.com`, then I get the value `somedomain.com.`in the DomainName.Value property in the MxRecord instance. Is that trailing `.` returned from the query soemwhere? Or is it being appended by mistake?

**Comment by MichaCo** [comment]
By design (RFCs) , labels in a DNS name are terminated with a dot.
So yes, you can always expect a dot at the end of a domain name in those cases. 
That's just how the data actually looks like which gets send back and forth between a DNS server and client.
