### ISSUE TITLE
Mock friendly API

### ISSUE THREAD

**Issue by MichaCo** [MichaCo/DnsClient.NET#2]
Adding/verifying usage and test-ability of the API

/cc @brantburnett

I just added interfaces over the most important things to make it easy to mock the `LookupClient` and query results in https://github.com/MichaCo/DnsClient.NET/commit/3787def48b6c63fc83f63e40a021290cca23e24c

There is also an example unit test which I used to test testing ~~

````csharp
// arrange
var lookupMock = new Mock<IDnsQuery>();

var aRecord = new ARecord(new ResourceRecordInfo("any", ResourceRecordType.A, QueryClass.IN, 0, 0), IPAddress.Any);

var responseMsg = new DnsResponseMessage(new DnsResponseHeader(123, 256, 1, 1, 0, 1), 123);
responseMsg.Answers.Add(aRecord);
IDnsQueryResponse dnsResponse = responseMsg.AsQueryResponse(new NameServer(NameServer.GooglePublicDns));

//// or mock response
//var dnsResponseMock = new Mock<IDnsQueryResponse>();
//dnsResponseMock
//    .Setup(p => p.Answers)
//        .Returns(new DnsResourceRecord[] { aRecord });
            
Task<IDnsQueryResponse> response = Task.FromResult(dnsResponse);
lookupMock.Setup(f => f.QueryAsync(It.IsAny<string>(), QueryType.A)).Returns(response);
var lookup = lookupMock.Object;

// act
var result = await lookup.QueryAsync("any", QueryType.A);

// assert
Assert.Equal(1, result.Header.AnswerCount);
Assert.Equal("any.", result.Answers.First().DomainName);
Assert.Equal(IPAddress.Any, result.Answers.ARecords().First().Address);            
 ```` 

I will leave this issue open for more feedback/comments.
Thanks ;)

**Comment by codan-prices** [comment]
Now that DnsResponseMessage is internal, this unit test no longer works. 
Is there an alternative way returning a fake responseMsg?

**Comment by MichaCo** [comment]
All types returned and the client itself implements interfaces.
So, yes, you can mock all of that or implement "test" versions of those interfaces which do what you need in your unit tests.
