### ISSUE TITLE
REFUSED doesn't cause retry

### ISSUE THREAD

**Issue by gregmac** [MichaCo/DnsClient.NET#20]
If a query gets the response REFUSED from a name server, LookupClient doesn't retry the query against any other servers.

Is this intentional behaviour?

The trouble I'm running into with this when a client has, for example, hardcoded DNS servers pointing at their (not current) ISP (think laptop/wifi) and the ISP DNS refuses queries from anything but the ISP network. I've also seen this happen with VPN, where a client connects over a VPN but continues to use the ISP DNS server (which no longer works since traffic comes from the VPN's network). 

Since the ISP DNS servers return REFUSED for everything, queries fail even when the client has other DNS servers that are working.

**Comment by gregmac** [comment]
Looks like retries only handle on:

* [TimeoutException](https://github.com/MichaCo/DnsClient.NET/blob/63ca18adb333114fc09db1a9edb2d3f6dc3eceb7/src/DnsClient/LookupClient.cs#L380)
* or "Transient" which means [SocketException](https://github.com/MichaCo/DnsClient.NET/blob/c7ee394eb4b69a2141049496b42240fc135c21f5/src/DnsClient/DnsUdpMessageHandler.cs#L26)
* [OperationCanceledException || TaskCanceledException](https://github.com/MichaCo/DnsClient.NET/blob/63ca18adb333114fc09db1a9edb2d3f6dc3eceb7/src/DnsClient/LookupClient.cs#L388)

**Comment by MichaCo** [comment]
Hi @gregmac, that's a valid case. 
One option would be to try out all configured servers until we get a valid result. That could cause a lot of overhead/traffic though. I'm actually not sure yet if the library should really do that.

A workaround for now could be to disable "throw on DNS errors" and retry yourself.

**Comment by gregmac** [comment]
For my use that's exactly what I'm going to do -- just handle the retries in the calling code. This gives more flexibility anyway, in both sequence, number of retries per server, and logging of errors. 

Just as an experiment, I did a couple tests with Windows 10 (10.0.136299), with a server that returns REFUSED as the primary and a working secondary server, and also with a non-DNS server IP as primary, followed by REFUSED, followed by working. 

In both cases, when I do lookups in a browser or even `ping` requests, there's always a query to each server, in order, until the final one responds with the correct request. 

Using `dig`, it gives up as soon as the first server responds with REFUSED.

**Comment by MichaCo** [comment]
Yup, I agree. It is more flexible.

For the future, I think I could change `ThrowDnsErrors` to a flag for server error handling
* throw the error (as today)
* return response with DNS errors (as today)
* or continue/try next server (new)

But that would be a bigger and a breaking change and the error handling is non-trivial already.

Maybe I should also add a configuration for using the server list always in order or cycle through/changing order each time..

**Comment by gregmac** [comment]
I would suggest not changing `ThrowDnsErrors`. Right now it controls whether it throws exceptions or not, which is orthogonal to what should cause a retry or not (for example, after retrying and exhausting all servers, does it throw or not?), plus it's not really worth a breaking change.

As a thought:

* `RetryOn` = Flags
  * `Timeout` (default)
  * `Refused` 
  * `ServerFailure`
  * Could also have a `RetryOnFlag.All => Timeout | Refused | ServerFailure` 
* `ServerListBehaviour` = Enum
  * `Balance`: cycle through all for each request (current, default)
  * `PreferFirst`: always start at first in list, and only try the next server on error/timeout 

However, I recognize this is a non-trivial effort, and if there's no one else that really needs this level of control it's probably not worthwhile.

**Comment by MichaCo** [comment]
@gregmac 
I decided to give it a try and I'm currently adding two flags to `ILookupClient`
* `bool PreserveNameServerOrder`: This can be used to prevent cycling through the nameservers in random order on consecutive calls
* `bool ContinueOnDnsError`: If enabled, the client will continue to query the next DNS server(s) until we either get a valid result or all of them returned a result with a DNS error (or couldn't be reached).
If `ThrowOnDnsError` is also enabled, the last error will be thrown in case non of the servers returned a valid result.

Initial testing seem to look pretty promising.
The audit trail will also contain all "retries" now.

I think those 2 new flags are clear enough and I don't have to add more complex flags as you suggested.

Let me know what you think or if that would not solve your problems
Thanks

**Comment by gregmac** [comment]
Yeah, those two options sound like they'd do the trick.

Minor naming issue, but personally I think an enum is clearer than `PreserveNameServerOrder`, because while it's obvious what that does in the `true` case (without looking at docs), it's not obvious what it does in the `false` case.

**Comment by MichaCo** [comment]
@gregmac agree with the name not being very clear, renamed it to `UseRandomNameServer` (inverting the logic). Actually like it better now
