### ISSUE TITLE
Eliminate dependency on Microsoft.Win32.Registry for newer TFM

### ISSUE THREAD

**Issue by thompson-tomo** [MichaCo/DnsClient.NET#208]
### Summary
In the newer TFM, Microsoft.Win32.Registry is included as part of the framework hence there is no need for an explicit dependency

### Proposal
When the TFM provides the library there is no need to add the dependency hence Microsoft.Win32.Registry would not be required for atleast net 8 but likely net 5+

**Comment by MichaCo** [comment]
That's already the case on the dev branch
