### ISSUE TITLE
Why would DnsClient be slower than raw nslookup?

### ISSUE THREAD

**Issue by hammypants** [MichaCo/DnsClient.NET#21]
Deployed on Win7. Targeting .NET Core 2. NuGet package v1.0.7.

`lookup.QueryAsync(domain, QueryType.MX)` is taking ~20s to resolve while a similar `nslookup` is nigh instantaneous (closer to what I expected). This runs blindingly fast on all the examples online I see, so I feel like it must be a configuration issue on my end? I just have no idea where to look.

Update:
It's taking almost exactly the amount of time I set the `Timeout` property on `LookupClient` to:
```
var lookup = new LookupClient(IPAddress.Parse("8.8.8.8"), IPAddress.Parse("8.8.8.4"))
{
	Timeout = TimeSpan.FromMilliseconds(500)
};
...
var result = await lookup.QueryAsync(domain, QueryType.MX);
// ~500 ms to run
```

**Comment by MichaCo** [comment]
You are not using the same dns server with nslookup I guess. And you get a timeout because the LookupClient triest to connect to `8.8.8.4` which doesn't exist. `8.8.4.4` would be the correct secondary public google DNS
