### ISSUE TITLE
MiniDig Sample "Your project targets multiple frameworks."

### ISSUE THREAD

**Issue by ChrisEelmaa** [MichaCo/DnsClient.NET#28]
If I try to run MiniDig example, I get error:

```
Chriss-MBP:MiniDig chriseelmaa$ dotnet run -s localhost micha.mcnet.com any
Unable to run your project
Your project targets multiple frameworks. Please specify which framework to run using '--framework'.
```

If I run this, it works:

```
dotnet run -f netcoreapp2.0 -s localhost hacken.io  any
```

**Comment by ChrisEelmaa** [comment]
Sure, I forgot to mention that it would be good idea to update README.md to demonstrate the actual code you have to use in order to run the example (currently is using without targeting framework). Took me some time to figure it out 😄

Or maybe set the target framework to be the same across the projects in minidig

**Comment by MichaCo** [comment]
Feel free to update the readme and push a PR for that ;)
