### ISSUE TITLE
Why enforce UseStd3AsciiRules

### ISSUE THREAD

**Issue by sjkp** [MichaCo/DnsClient.NET#31]
Why do you force the 
 new IdnMapping() { UseStd3AsciiRules = true }; in DnsString.cs ? 

I would like to use your library to do dns queries with international domain names containing other than ascii characters, but that hardcoded value effectively stops that. At least could it be an option that we can set? 

I'm not a dns expert but as far as i can read from the standard https://tools.ietf.org/html/rfc3490#page-10 it should be okay. 

I tested relaxing the rule, and it works fine in my case, but I would really prefer not to have to create my own version of the library.

**Comment by MichaCo** [comment]
Yeah I did some testing myself some time ago and think we can just change that. 
Not really sure anymore why this was restricted like that in the first place

**Comment by MichaCo** [comment]
There is a new beta package DnsClient.1.1.2-beta-1174 on myget. If you want, try it out

**Comment by MichaCo** [comment]
/closed
This has been updated and released in 1.2
