### ISSUE TITLE
Problem with AXFR Zone Transfers

### ISSUE THREAD

**Issue by TrevorWesterdahl** [MichaCo/DnsClient.NET#32]
I have a problem with the AXFR (zone transfer) query results. Not all records are returned.

First, I want to say that I am querying an internal DNS server and the machine running the query has its IP approved for zone transfers on the DNS server. In one zone, I have over 2,000 DNS entries and only about 1/4 (466) of them are returned. The smaller zones seem to transfer fine. The results literally arrive in order and stop at a particular entry and the rest of the records are not retrieved.

There are no errors... the results come back as though they were returned complete. I don't know what the issue is, but it seems like the query stream may be quitting mid-retrieval, like there is a buffer problem, or perhaps large zone transfers are split into multiple transfers but its not handled, or perhaps an error is triggering a cancellation of a complete transfer but is swallowed somewhere. I don't know.

NOTE: The computer that is running the DNSClient code can retrieve all the records using nslookup. I was originally using the version of DNSClient from nuget, but downloaded the source code to try and resolve this. Within the method, within the class DnsMessageHandler: 

public virtual DnsResponseMessage GetResponseMessage(ArraySegment<byte> responseData)

The variable, 'response', contains the 466 answers. If I look at the 'reader' variable, it seems to always have an index size of 16371. Don't know if this a variable size issue, or a size issue on the response from the DNS server. I'm sure you know how to debug this better than I do. Willing to help to resolve this.

**Comment by MichaCo** [comment]
Hi @TrevorWesterdahl 
Turns out, the DNS server can actually send multiple complete responses with header, answers etc.
I added some code to continue reading from the TCP stream in case there is more data and then to combine the resulting messages.

I was able to reproduce it and test that the changes work.

You can test the latest beta package if you want, to check if that solves your issue.

**Comment by TrevorWesterdahl** [comment]
I would be happy to test out the beta version.

**Comment by MichaCo** [comment]
https://www.myget.org/feed/dnsclient/package/nuget/DnsClient

**Comment by TrevorWesterdahl** [comment]
I installed beta version 1176 from nuget and tested. Issue appears to be resolved. All records were retrieved and counts match nslookup results.

Thank you, much appreciated! Let me know when the official version (non-beta) is released.
