### ISSUE TITLE
Using ResolveServiceProcessResult looses important information

### ISSUE THREAD

**Issue by RobThree** [MichaCo/DnsClient.NET#34]
When using the [`ResolveService`](https://github.com/MichaCo/DnsClient.NET/blob/aee73c30c2e3a302a80db32a9d04f70d17f35d30/src/DnsClient/DnsQueryExtensions.cs#L559) method, or it's ['Async counterpart'](https://github.com/MichaCo/DnsClient.NET/blob/aee73c30c2e3a302a80db32a9d04f70d17f35d30/src/DnsClient/DnsQueryExtensions.cs#L599), a result with hosts and ports is returned which is fine, but the `priority` and `weights` are lost in the results. Big part of the point of SRV records is being able to know [in which order and with what preference to approach which host](https://en.wikipedia.org/wiki/SRV_record#Provisioning_for_high_service_availability).

If I may make a suggestion then I'd prefer DnsClient to simply return `priority`, `weight` and `ttl` for these methods. Alternatively, a structure that contains the results in sorted groups and sorted priorities within the groups is also an option.

**Comment by RobThree** [comment]
> Those methods are meant for convenience / to simplify the resolve part.

That was clear to me 😉 

> Priority, weight and ttl could be added to that as properties, too I guess.

That was, sort of, the intent of my question indeed.

> That being said, the resolved result will already be ordered, you don't usually have to do that again.

I don't see any explicit ordering being done? Or I'm missing it?

> A DNS Server usually decides to re-order results to give you some kind of load balancing (e.g. in case there are multiple endpoints for the same service).

The priority and weight are intended **for clients** to be able to determine which record to pick. Assume the following SRV:

    prio 0 :   weight: 10   port: 9991  host: hostA.example.org
    prio 10:   weight: 10   port: 9992  host: hostB.example.org
    prio 10:   weight: 40   port: 9993  host: hostC.example.org
    prio 10:   weight: 50   port: 9994  host: hostD.example.org
    prio 20:   weight: 1    port: 9995  host: hostE.example.org
    prio 20:   weight: 9    port: 9996  host: hostF.example.org

A client should first try host A (highest priority, only one in it's "group"). If host A fails, the client should pick one from hosts B, C or D with a 10% 'chance' of picking host B, 40% chance of picking host C and 50% chance of picking host D. Of the picked host (either B, C *or* D) fails again, the next priority group should be used: hosts E and F. Again, the client should choose between E or F by using a 10% chance of picking E and 90% chance of F.

This is how the 'load balancing' works. The weights and priorities determine when, and how often, a host should be used (assuming the client respects the actual SRV record, ofcourse).

So you see, when using SRV records you will *need* the priority and weights (the TTL _can_ be useful to 'have' to, but I can live without).

I can do the SRV query just fine, don't get me wrong; I simply use `myLookup.Query("_service._tcp.example.com", , QueryType.SRV)` and that works fine. I just think it's odd that the `ResolveService` extensionmethod gets rid of the information required for clients to work properly.

I will shortly post a proposed implementation of the `ResolveService` extensionmethod which, I think, is better suited. Ofcourse, it's up to you to decide wether you like to use it or ignore it 😉

**Comment by MichaCo** [comment]
I think the simplified implementation came mostly from me using this together with Consul for service discovery. Consul's DNS endpoint always returns filtered and weighted entries already.

But you are right, for other use-cases that information (prio/weight) is needed.
Sure, go ahead and send a PR ;)

**Comment by MichaCo** [comment]
> I used IEnumerable<...> everywhere, you may prefer arrays or other ... enumerables 😜 (hell, IEnumerable<...> may cause some issues).

Right, I don't like to use IEnumerable for those kind of things, especially because it gives kinda random results every time it gets iterated ;)

I think, for this library, it is enough to have the existing methods and just extend the returned `ServiceHostEntry` to contain the missing fields (this would be a non-breaking change)

I'd rather not implement any logic on top of that within this library and leave that up to consumers.
You could use it with the example you have there, or do something totally different ;)

**Comment by MichaCo** [comment]
Hey @RobThree 
Just revisited this one again, I think the simplest solution is when I add the original `SrvRecord` to the `ServiceHostEntry`

```csharp
    public class ServiceHostEntry : IPHostEntry
    {
        public int Port { get; set; }

        public SrvRecord SrvRecord { get; set; } <== NEW
    }
```

The SrvRecord has the weight and prio on it so you can further filter/sort the results after calling `ResolveService`.

What do you think?

**Comment by RobThree** [comment]
> What do you think?

It's been a while since I opened this issue. I'll need to dive back in the matter and (re)familiarize myself.

From what I see right now: A SRV lookup results in one or more `ServiceHostEntry` objects (or none); each `ServiceHostEntry` each having it's own `AddressList[]`....

Without looking up anything, only basing my opinion on information in this issue...

Wouldn't an SrvRecord property make it awkward to get to the weight and priority? I can get straight to the port and addresslist (which always will contain one, and only one, address, right?) but would have to use the SrvRecord property to get to the Priority and Weight?

Why not:

```c#
public class ServiceHostEntry : IPHostEntry
{
    public int Port { get; set; }

    public int Priority { get; set; }
    public int Weight { get; set; }
}
```

I may be way off base though; as said: it's been a while and I'd have to look longer/deeper. I will, but am currently a bit (too) busy.

**Comment by MichaCo** [comment]
Thanks for the reply ;)
That actually makes more sense, yup
