### ISSUE TITLE
QueryAsync failing?

### ISSUE THREAD

**Issue by mhingston** [MichaCo/DnsClient.NET#37]
DnsClient: 1.2.0
.NET Framework 4.7
Visual Studio 2017 Professional

Using the simplest example, the `QueryAsync` method is failing for me? If I step through the code the program exits unexpectedly (no exception) on the line with the `await`.

```csharp
using DnsClient;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Main();
        }

        static async Task Main()
        {
            var lookup = new LookupClient();
            var result = await lookup.QueryAsync("google.com", QueryType.ANY);

            var record = result.Answers.ARecords().FirstOrDefault();
            var address = record?.Address;
        }
    }
}
```

If I change from `QueryAsync` to `Query` and remove the `await` the program runs as expected.

**Comment by gschuermans** [comment]
The async calls look fine. You'd still have to Wait() for the async invocation. Otherwise the console app would just terminate.

**Comment by MichaCo** [comment]
That's correct, your main method doesn't await the `async Main()` and therefore just exits. You can either synchronously await the method or let `Console.ReadLine` do its thing,
