### ISSUE TITLE
Add "motivation" or "comparison to System.Net.Dns" to readme?

### ISSUE THREAD

**Issue by Jehoel** [MichaCo/DnsClient.NET#40]
Ordinarily I use `System.Net.Dns` which is included in .NET Core 1.0+, .NET Framework, and .NET Standard 2.0+ - I was referred to using this library from a StackOverflow post specifically for performing `MX` lookups (to validate e-mail addresses in an account registration page on a website I'm working on) and I was looking for a quick explanation of why I should use `DnsClient.NET` instead of `System.Net.Dns` and after reading the docs for about 10 minutes now I still feel like I'm missing out on something.

I know `System.Net.Dns` is lacking some functionality, like the ability to perform true `async` queries for DNS records other than `A`/`AAAA` records - but 95% of my use-cases are met by the built-in class.

So a quick feature-comparison or statement-of-motivation (i.e. why you built this) would really help the introductory documentation for this project, imo.

**Comment by MichaCo** [comment]
System.Net.Dns only resolves host names or IPAddresses to names and uses the operating system's resolver as far as I know. It might not really ask your DNS server.
DnsClient can query any DNS Server on any port and you can query for any record type. 
If you don't need that, don't use it ;)
