### ISSUE TITLE
Https http://dnsclient.michaco.net/

### ISSUE THREAD

**Issue by 304NotModified** [MichaCo/DnsClient.NET#42]
Hi,

It would be nice if dnsclient.michaco.net is available on https. Now we get:

![image](https://user-images.githubusercontent.com/5808377/52209770-36671f00-2885-11e9-91f7-35c0faaba00b.png)

It's correct that you are using Azure? Maybe this could be helpful: https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/20047

**Comment by MichaCo** [comment]
Hey,
Yeah I know, I could use lets encrypt. Just haven't had time to setup the deployments and get everything running and tested...

Will happen eventually

**Comment by 304NotModified** [comment]
🎉
