### ISSUE TITLE
Why does the SOA record not contain a collection of name servers?

### ISSUE THREAD

**Issue by davidpeden3** [MichaCo/DnsClient.NET#43]
[SoaRecord.MName](http://dnsclient.michaco.net/docs/DnsClient.Protocol.SoaRecord.html) contains one of the (presumably the primary) name servers. I would expect there to be a collection of these rather than a single property.

When performing an `nslookup` command, I get the following results:

```
C:\>nslookup -q=soa hourstrackercloud.com
Server:  rdns.dynect.net
Address:  216.146.35.35

Non-authoritative answer:
hourstrackercloud.com
        primary name server = ns71.domaincontrol.com
        responsible mail addr = dns.jomax.net
        serial  = 2019030312
        refresh = 28800 (8 hours)
        retry   = 7200 (2 hours)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)

hourstrackercloud.com   nameserver = ns72.domaincontrol.com
hourstrackercloud.com   nameserver = ns71.domaincontrol.com
```

On the other hand, the following code:

```c#
var soaResponse = lookupClient.Query("hourstrackercloud.com", QueryType.SOA);
var nameServer = soaResponse.MName; #ns71.domaincontrol.com
```

only exposes one of the two name servers.

**Comment by MichaCo** [comment]
you should get 2 NS records back from `lookupClient` in your example

**Comment by davidpeden3** [comment]
So the type of query I did is `QueryType.SOA` and it only returns a single record (as expected for the query type). Having said that, I had not tried running a query of type `QueryType.NS`. That _does_ return two records as expected (and as your updated comment above shows).

Is it reasonable to expect the API surface for a `SoaRecord` to contain the related `NsRecord`s in the object graph? Personally, I think it's odd that it doesn't.

How does a `QueryType.NS` query work under the hood? I'm not familiar with your codebase but would appreciate it if you could point me in the right direction so I can better understand it.

Finally, is the best way to get the IP address of an `NsRecord` to do a subsequent `QueryType.A` for each `NsRecord` returned? I was surprised that it's also not available on the `NsRecord` itself.

**Comment by MichaCo** [comment]
The library doesn't do anything special. It returns whatever the DNS Server you are using returns.

There is always only one SOA record and it will return only the primary master NS server.
See https://en.wikipedia.org/wiki/SOA_record

To get all nameservers, you'll query for `NS` records.

There might be additional answers in the query result which resolve the FQNs of the nameservers. 
Public DNS servers usually don't recursively resolve answers though and you'd have to do that yourself.

**Comment by davidpeden3** [comment]
Got it. Thanks!
