### ISSUE TITLE
Any request problem

### ISSUE THREAD

**Issue by rserit** [MichaCo/DnsClient.NET#44]
Hi,
First at all thanks for this library.
I think i find a bug. When i query [this](http://www.isimtescil.net) domain as "any" query type, it has error but it has no error while i select query type like MX. I don't understand why i getting error.

Thanks,
Recep.

**Comment by MichaCo** [comment]
What DNS server do you use? What's the error you get?

**Comment by rserit** [comment]
Error message is "Server Failure". I don't use special DNS server address. But I also used Google DNS address. Result is same. I don't understand why it's just on this site.

**Comment by MichaCo** [comment]
Google's public DNS server returns `Server Failure` as response. 

Not much this library can do about that because that's just what the server returns.
I don't know exactly why this is, but you'd have to ask the DNS server host.

**Comment by rserit** [comment]
Also I sent request on [dnsclient.michaco.net](http://http://dnsclient.michaco.net/). Result is same. Is problem on website  host side? Should I ask to web host? :)
