### ISSUE TITLE
Question: Why is ResponseCache not using IMemoryCache?

### ISSUE THREAD

**Issue by oliverw** [MichaCo/DnsClient.NET#47]
Glacing over the source I'm wondering why you'd opted for a custom cache implementation instead of using the built-in MemoryCache?

**Comment by MichaCo** [comment]
That would add a dependency to Microsoft.Extensions.Caching and I cannot have that.
Also, I don't use any features of that cache so I don't need it.

**Comment by oliverw** [comment]
Fair enough. Thanks for the clarification.
