### ISSUE TITLE
Maximum cache duration?

### ISSUE THREAD

**Issue by Daniel15** [MichaCo/DnsClient.NET#48]
I see that there is a `MinimumCacheTimeout` option. Is there some way to have a corresponding maximum cache timeout? I want to just cache responses for a short period of time, rather than for their entire TTL.

**Comment by MichaCo** [comment]
No, there is no option for max duration yet. 
I agree, it would be a good thing though ;)

**Comment by Daniel15** [comment]
Thanks for confirming! My use case is that I want a cache with a fairly short cache duration in order to cache lookups that are very frequently performed, without wasting space in the cache for lookups that are not performed as frequently.

**Comment by MichaCo** [comment]
Hi @Daniel15, I added that feature with the latest PR, you can find [the setting / code here](https://github.com/MichaCo/DnsClient.NET/blob/dev/src/DnsClient/ILookupClient.cs#L430)
This will work the same way as the minimum setting but as a upper limit.
Is that what you had in mind?

**Comment by Daniel15** [comment]
Thanks! I'll take a look when I get some free time :)
