### ISSUE TITLE
DnsResponseException when using Library in PowerShell 5

### ISSUE THREAD

**Issue by floatingsidewalk** [MichaCo/DnsClient.NET#49]
There is a bug when using this with PowerShell v5

PS C:\temp\dnsvalidator> import-module .\DnsClient\lib\net45\DnsClient.dll
PS C:\temp\dnsvalidator> $dnsClient = new-object DnsClient.LookupClient
PS C:\temp\dnsvalidator> $dnsClient.Query("google.com", "A")
Exception calling "Query" with "2" argument(s): "Unhandled exception"
At line:1 char:1
+ $dnsClient.Query("google.com", "A")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DnsResponseException

Works great in Powershell 6/Core.

**Comment by MichaCo** [comment]
Try calling e.g. 
```

$dnsClient = new-object DnsClient.LookupClient
$dnsClient.EnableAuditTrail = "True"
try
{
 $dnsClient.Query("google.com", "A")
}catch [Exception]
{
 echo $_.Exception.GetType().FullName, $_.Exception.Message, $_.Exception.Code, $_.Exception.AuditTrail
}
```

This will maybe give you the actual exception which cause the failure.

I'm getting 

```
;; Error: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system canno
t find the file specified.
```
Which kinda makes sense but is annoying.
This means you also have to load that assembly alongside with DnsClient via import-module

import-module  ...lib\netstandard1.1\System.Buffers.dll

Seems to work fine for now for me
