### ISSUE TITLE
DNS Queries for SRV are timing out when upgraded from 1.1.1 to 1.2.0

### ISSUE THREAD

**Issue by TraGicCode** [MichaCo/DnsClient.NET#50]
We recently upgraded our version of MongoDB.Driver which also upgrade DnsClient from 1.1.1 to 1.2.0.  We are noticing the following errors being returned in our application logs and causing issues for users of our application.

```
A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Disconnected", Servers : [], DnsMonitorException : "DnsClient.DnsResponseException: No connection could be established to any of the following name servers: 10.0.3.22:53 (Udp: 512), 10.0.5.177:53 (Udp: 512), 192.168.1.45:53 (Udp: 512).
   at DnsClient.LookupClient.ResolveQuery(IReadOnlyCollection`1 servers, DnsMessageHandler handler, DnsRequestMessage request, Boolean useCache, LookupClientAudit continueAudit)
   at DnsClient.LookupClient.QueryInternal(IReadOnlyCollection`1 servers, DnsQuestion question, Boolean useCache)
   at MongoDB.Driver.Core.Misc.DnsClientWrapper.ResolveSrvRecords(String service, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.DnsMonitor.Monitor()" }.
```

Were there any huge changes around the above area in the new version?  Are we the only ones experiencing this issue?

**Comment by MichaCo** [comment]
Hi @TraGicCode,
I just double checked the commits from 1.1.1 to 1.2.0, but nothing has changed in the UDP query stack from 1.1.1 to 1.2.0.

The default [connection timeout](https://github.com/MichaCo/DnsClient.NET/blob/1.1.1/src/DnsClient/LookupClient.cs#L41) is 5 seconds which is quite a lot, and it seems that all servers timed out in your case.
It very likely has nothing todo with this library I'd say ;) Hard to tell though so let me know what else you find.

**Comment by TraGicCode** [comment]
Hey @MichaCo,

Sorry for responding to the wrong pull-request!

Closing. Turned out to be a DNS Server in DHCP that didn't get removed!
