### ISSUE TITLE
Unhandled exception "Record reader index out of sync." when record type 'OPT' received.

### ISSUE THREAD

**Issue by Regentag** [MichaCo/DnsClient.NET#55]
When you request a Type A record from the Cloudflare DOH server, a Type OPT record is returned along with the Type A record.
(I'm using Cloudflare DOH through Local DNS Proxy.)

Currently DnsRecordFactory.GetRecord method is checking _reader.Index value. Therefore, the value of _reader.Index should be updated when processing records, but "Record reader index out of sync." exception occurs because there is no code associated with processing Type OPT records.

related pull req' : #54

**Comment by MichaCo** [comment]
Thanks for the PR and reporting the issue.

That behavior is pretty odd though, the requested OPT record isn't supposed to transport any data...
Do you get multiple OPT records or just one with some RDATA bytes?

That being said, it was a mistake to not read / or at least advance the reader if `RDLEN` is not zero.

I'll fix that in a slightly different way though and might close your PR afterwards.
I'll read the bytes and keep them in the OPT record in case someone wants to work with that data.

Related to #11 I guess:
I'm also making the OPT record public and will keep all OPT records in the response (Additionals)! 
(So far, I always removed the EDNS OPT record from the response)

**Comment by Regentag** [comment]
![opt_record_debug](https://user-images.githubusercontent.com/9898837/75624439-7408b980-5bf7-11ea-80df-849491f323e6.png)

**Comment by MichaCo** [comment]
@Regentag could you double check if the latest beta package of DnsClient from [Myget](https://www.myget.org/feed/dnsclient/package/nuget/DnsClient) works for you, that would be great ;)

**Comment by Regentag** [comment]
@MichaCo 
I'm sorry I couldn't respond quickly. I'm away from home for personal reasons, and I think it'll take a few weeks to get back.
I'll test it when I get home.

**Comment by MichaCo** [comment]
The fix is not release on NuGet https://www.nuget.org/packages/DnsClient/1.3.0
