### ISSUE TITLE
DNS query is only checking one DNS server per request.

### ISSUE THREAD

**Issue by toddschilling** [MichaCo/DnsClient.NET#6]
I'm not sure how the RFC reads, so I may be wrong about how the client is supposed to behave. It seems like a single query should automatically move through all name servers in the list even if one server returns Non-Existent Domain.

Let's say that I have 2 name servers configured at the OS, where 1 is valid for the domain and the other has no knowledge of the domain.

`ns1 - has entry for host1.mydomain.`
`ns2 - does not have any knowledge of .mydomain.`

The way that the client works now is that if I create an instance of the client and execute a query for `host1.mydomain.`, it will work.  Then, if using the same instance of the client, I make another query for `host1.mydomain.`, it uses ns2 and fails returning no records.

**Comment by MichaCo** [comment]
Hi @toddschilling yeah the behavior you describe is how it is implemented right now. Configuring the LookupClient with multiple DNS endpoints is meant for a) load balancing and b) fail-over in case one of those servers is not available; I'm totally expecting that all configured servers would return consistent results.

In general, I think it would be pretty bad for performance, if I would query all servers and eventually none of them can resolve the domain name. That's a lot of extra traffic.

That being said though, I have to investigate what/if the RFC says in that regards, not 100% sure tbh. 

There might be some functionality needed in case the response returns "recursion not available", in that case the client could either ask another server or check the response for dns servers I could query to get a result...

Thanks and let me know what you think ;)
m

**Comment by toddschilling** [comment]
Thanks for the response.  I do somewhat agree with what you're saying.  The fact that my DNS servers aren't properly forwarding requests could the real issue.  Solving that would at least give consistent behavior.

I'm going to close this but will check the RFC as well.  Please post here if you have a definitive answer from the RFC.
