### ISSUE TITLE
How to new LookupClient with old LookupClientOptions?

### ISSUE THREAD

**Issue by rmbolger** [MichaCo/DnsClient.NET#72]
I'm fairly new to the library, but liking it a lot so far. Thanks for the effort in maintaining it!

I'm currently playing with it directly from PowerShell and trying to figure out if there's a way to create a new instance of `LookupClient` with different nameservers, but copy the settings from my old instance. I'm trying to avoid having to create an empty `LookupClientOptions` and then copy the values to it individually from the old instance's settings.

Something like a `LookupClientOptions` constructor that takes a `LookupClientSettings` object....or maybe a static method like `LookupClientOptions.FromSettings()`. Is there something obvious I'm missing?

P.S. I know about the `QueryServer*` methods for one-off queries against other nameservers. This would be for a more long term change.

**Comment by MichaCo** [comment]
Creating an oiptions instance from settings doesn't exist because you can just keep an instance of `LookupClientOptions` which your code handles and updates. And then, every time you change the options, you also have to create a new instance of LookupClient with those options.

That should work in your case too maybe? Instead of using the readonly settings of the client instance, just keep an options variable somewhere?

**Comment by rmbolger** [comment]
Hah, yes. That would be the obvious thing I was missing. Thanks!

> Just out of curiosity, what are you doing with it in powershell?

G

**Comment by rmbolger** [comment]
Wait no, I think I'm still missing something.

`LookupClientOptions.NameServers` is read-only. And `LookupClient` doesn't seem to have a constructor that takes a `LookupClientOptions` instance *and* a separate set of nameservers. So if I want to keep the existing options, I'm also stuck with the current nameserver list, no?

In my head, the use experience I'm going for is something like this. When the module loads initially, a `LookupClient` is spun up with default settings and the system's nameserver list. There's a main function like `Resolve-Dns` that you can use with or without an explicit nameserver list. For example:

```powershell
Resolve-Dns example.com CAA
Resolve-Dns example.com CAA -NameServer 8.8.8.8
```

No problem so far. We can just use `QueryServer` instead of `Query` any time they specify explicit nameservers. However, there will also be a function to tweak the LookupClient settings such as `Set-DnsClientSetting` which would have options to tweak the various settings *and* the default nameserver list.

```powershell
# module loads with default settings using system nameservers

# use turns off recursion and makes queries
Set-DnsClientSetting -Recursion:$false
Resolve-Dns example.com CAA

# user changes default nameservers and makes additional queries
# with same client options as before
Set-DnsClientSetting -NameServer 8.8.8.8
Resolve-Dns example.com CAA

# user switches back to default nameservers
Set-DnsClientSetting -UseDefaultNameserver
```

I suppose I could just keep a copy of the active nameserver list around and just use that via `QueryServer` unless an explicit list was specified in the function call. But for some reason that feels wrong.

**Comment by MichaCo** [comment]
Ah, yeah right, forgot about that ^^

The reason for making the name servers readonly is relatively stupid. Maybe we should make it writeable. Options are supposed to be writeable.

The list of servers is readonly because of the server auto discovery flag.  
I didn't want to have the user have to set that to false if they'd add servers after instantiating the options object. That flag is then used later on by the client to determine if it should use the system's DNS servers.

**Comment by rmbolger** [comment]
I figured it might have been related to having the cache tied to the current nameservers. And so being able to change them would/should invalidate that cache if it exists.

**Comment by MichaCo** [comment]
Cache is not bound to the source nameserver(s) (anymore). So that shouldn't be an issue

**Comment by rmbolger** [comment]
In any case, yes. Having nameservers settable on the options object would definitely solve my problem.

**Comment by TropicalThunder** [comment]
You can do something like this:

` private static readonly IPAddress[] _servers = new[]
        {
            IPAddress.Parse("1.1.1.1"),
            IPAddress.Parse("1.0.0.1"),
            IPAddress.Parse("8.8.8.8"),
            IPAddress.Parse("8.8.4.4"),
            IPAddress.Parse("208.67.222.222"),
            IPAddress.Parse("208.67.220.220")
        };

        private readonly LookupClient _client;

        public DnsLookupService()
        {
            var options = new LookupClientOptions(_servers)
            {
                UseCache = false,
                ThrowDnsErrors = true,
                UseRandomNameServer = false
            };

            _client = new LookupClient(options);
        }`

**Comment by rmbolger** [comment]
I also just realized that not all of the `LookupClient` settings are settable directly on an existing instance and the ones that are settable are marked as obsolete. So it seems like the intention is for LookupClient to be immutable once instantiated.

The way I'm currently handling things in order to future proof myself is to keep an instance of `LookupClientOptions` with the default nameservers which is used to create a fresh `LookupClient` anytime someone changes a setting. There's also an "active" nameservers list which gets used via `QueryServer*` methods.

The only minor downside (or feature depending on perspective) is that changing any setting empties the cache since a new `LookupClient` instance is created. But I'm also disabling cache by default, to make things work more like dig/nslookup. So it shouldn't affect too many people.

**Comment by rmbolger** [comment]
@MichaCo I've got a basic v1 version of the module released now. Thanks again for the library and the help.

https://github.com/rmbolger/DnsClient-PS
