### ISSUE TITLE
SocketException (10049) in IPv6 Environment

### ISSUE THREAD

**Issue by yang-er** [MichaCo/DnsClient.NET#74]
https://github.com/MichaCo/DnsClient.NET/blob/21ca5260f27bcfdecf0be8346a0d3c6f929f2371/src/DnsClient/NameServer.cs#L166

Here, if a nameserver [::]:53 is used, it will be converted into :::53, which makes throw System.Net.Sockets.SocketException (10049): AddressNotAvailable

It may be fixed by
```csharp
public override string ToString()
{
    return AddressFamily == System.Net.Sockets.AddressFamily.InterNetworkV6 ? $"[{Address}]:{Port}" : $"{Address}:{Port}";
}
```

**Comment by MichaCo** [comment]
Hi @yang-er,
The `ToString` method of `NameServer` is not used anywhere in this library and is purely cosmetic for logging for example. How do you get that exception?

**Comment by yang-er** [comment]
I'm sorry I've mistaken this. Then I have no ideas about this exception.

```csharp
public LookupClient Client { get; } = new LookupClient(new LookupClientOptions
{
    UseTcpOnly = true,
});

public async Task DigCnameChainAsync(string hostname, string _)
{
    hostname = hostname.TrimEnd('.');
    var here = ZoneRecord.Root.GetChildren(hostname);
    var resp = await Client.QueryAsync(hostname, QueryType.ANY);
    var cname = resp.Answers.OfType<CNameRecord>().SingleOrDefault();

    while (cname != null)
    {
        hostname = cname.CanonicalName.Value.TrimEnd('.');
        var there = ZoneRecord.Root.GetChildren(hostname, false);
        if (there.LinkedTo != null) return;
        here.LinkedTo = there;
        here = there;

        resp = await Client.QueryAsync(hostname, QueryType.ANY);
        cname = resp.Answers.OfType<CNameRecord>().SingleOrDefault();
    }
}
```

This is my code to dig the CNAME chain. This situation got worse when `UseTcpOnly` was set to false. Is this just my network issue?

**Comment by MichaCo** [comment]
I don't see how the code you posted uses NameServer in any way. Your are not specifying any servers to query, which means the LookupClient will just use whatever DNS Server is defined in your local network.
So, what line exactly throws the error you reported?

**Comment by yang-er** [comment]
Just when calling `await Client.QueryAsync`. 

I think it's almost my network issue. But it is funny that it became much easier to throw this exception when use `QueryType.CNAME` instead of `QueryType.ANY`.

**Comment by yang-er** [comment]
https://github.com/MichaCo/DnsClient.NET/blob/21ca5260f27bcfdecf0be8346a0d3c6f929f2371/src/DnsClient/NameServer.cs#L253

I think the problem comes from here. When I remove the nameserver entry of `[::]:53`, the library works pretty well.

This strange problem also breaks `nslookup` in Windows. It looks like a problem with Windows VPN. I think you can add this filter condition if you like.

**Comment by MichaCo** [comment]
The IPv6 address `::` is equivalent to the IPv4 `0.0.0.0` address. Both are not a "real" addresses and never get routed.
It is usually used to indicated "any address" but cannot really be used in the context of specifying a DNS server endpoint.

So, the question would be why your network adapter is configured with a DNS server pointing to 0.0.0.0, that's probably misconfigured?
You could check `Ipconfig /all` to see what `GetAllNetworkInterfaces` would return in your case.

That being said, its probably better to filter the "any address"s, and I'll add that.
In your case you would then probably just get a different error from this library if there is no other usable DnsServer is configured in your network.

**Comment by yang-er** [comment]
```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : ******-*******
   Primary Dns Suffix  . . . . . . . : *******.corp.*********.com
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : corp.*********.com

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : corp.*********.com
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (3) *******
   Physical Address. . . . . . . . . : **-**-**-**-**-**
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : **-**-**-**-**-**
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : **-**-**-**-**-**
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Dual Band Wireless-AC ****
   Physical Address. . . . . . . . . : **-**-**-**-**-**
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : *************************(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.***(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : 2020年6月3日 19:18:02
   Lease Expires . . . . . . . . . . : 2020年6月6日 21:40:44
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 1053*****
   DHCPv6 Client DUID. . . . . . . . : ****************************
   DNS Servers . . . . . . . . . . . : 192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : **-**-**-**-**-**
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : ***************************(Preferred)
   Link-local IPv6 Address . . . . . : ***************************(Preferred)
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 8388****
   DHCPv6 Client DUID. . . . . . . . : ***********************************
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : *****************
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : ********************(Preferred)
   IPv4 Address. . . . . . . . . . . : *********(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : ************
   DHCPv6 Client DUID. . . . . . . . : ****************************************
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

For some reasons, I have replaced some informations with `******`.

I think it is caused by the VPN provider, and I have no way to configure it. When I turn off the VPN, it will not detect `[::]:53`.

**Comment by MichaCo** [comment]
Thanks for posting your configuration.

For whatever reason it doesn't really explain why the filtering done by  `NameServer.ResolveNameServers` would produce a result with a [::] address though. I don't see that DNS Server configured in any of your interfaces.

Your main WIFI interface has `DNS Servers . . . . . . . . . . . : 192.168.1.1` configured, which looks very correct, pointing to your router I guess. And that one should be the only one used/found.

Just wondering, was this really with enabled VPN?

**Comment by yang-er** [comment]
Yes. The VPN really works (in China?...)

It uses a strange application (maybe UWP?) to configure the network settings, and is not configured by "Add VPN" dialog in Windows.

**Comment by MichaCo** [comment]
Mh, well, ok, that's probably impossible for me to reproduce/understand then ;)
Thanks anyways!

I'll make some changes to improve the filtering
