### ISSUE TITLE
Zone Transfers (AXFR) with TSIG auth?

### ISSUE THREAD

**Issue by rmbolger** [MichaCo/DnsClient.NET#81]
I've recently found myself needing to do some zone transfers using TSIG auth with HMAC-SHA256 keys. Based on the docs, I'm pretty sure DnsClient.NET doesn't support this unless I've overlooked something. Has there been any consideration to add this to the library? I'm more or less looking for a programmatic version of this dig command:

```
dig @ns.example.com axfr example.com -y HMAC-SHA256:mykey:XXXXXXXXXXXX
```

**Comment by MichaCo** [comment]
I haven't planned adding auth features mostly because I'm not sure how complex those are to implement and haven't looked into it too much...

I was planning to make the library more extensible though, so maybe there will be some way to do stuff like that in the future.
