### ISSUE TITLE
Incorrect product versions in releases

### ISSUE THREAD

**Issue by DmitryLukyanov** [MichaCo/DnsClient.NET#92]
It looks like at least the releases that I checked (1.3.1 and 1.3.2) contain the wrong `ProductVersion`s. 
- 1.3.1:
![image](https://user-images.githubusercontent.com/44870738/98138820-8b115100-1ed4-11eb-83c7-11d8f4caabc9.png)
- 1.3.2:
![image](https://user-images.githubusercontent.com/44870738/98138985-b85dff00-1ed4-11eb-98e6-edcd72551eeb.png)
Pay attention that they contain `beta` suffices which is wrong since the mentioned releases are not beta (at least anymore).

This can confuse from time to time because some applications include such information(ProductVersion) into their logs and then it's unclear why the referenced version is `1.3.1`, but the actually used version mentions `beta` .

**Comment by MichaCo** [comment]
Should be fixed in 1.4.0

**Comment by MichaCo** [comment]
Was a bit a pain in the ass to adjust the azure build/release pipelines correctly, but it looks like it worked.
Getting the following assembly version from the non beta package
(via ILSpy)

![image](https://user-images.githubusercontent.com/5837539/107882418-7b4cd400-6ee9-11eb-9c23-e370500a15af.png)
