### ISSUE TITLE
1.4.0 release ETA

### ISSUE THREAD

**Issue by shivinsky** [MichaCo/DnsClient.NET#94]
Are there any plans for a new version? Waiting for #87 get released.

**Comment by MichaCo** [comment]
Hey, I'm currently pretty busy with work but I might have some time again in December, during vacation..., probably not before mid/end Dec.
I was planning to release and finish 1.4 and more much earlier, but hey, shit happens

**Comment by MichaCo** [comment]
plan is to finally wrap up 1.4 this weekend 2/13
