### ISSUE TITLE
Display all records\addresses

### ISSUE THREAD

**Issue by Beacon101** [MichaCo/DnsClient.NET#95]
Hello all,
Thanks for your time in advance.
Sorry if this is a simple question, I am new to coding and may have this completely wrong. 
I have an issue with displaying all records. All of the MX records seem to display and usually all A records (Dose for some domains but not for Google.com). However, I can't say the same for AAAA records. I did the test with google.com using Google DNS (8.8.8.8:53). I compared the result to your own "Try It Yourself" on your michaco.net page and to MXtoolbox and these get far more results. 

Below is a snippet of my code. Is this correct and am I using this right?

`      using System;
       using System.IO;
       using System.Linq;
       using System.Collections.Generic;
       using DnsClient;
       using System.Net;

        string DNS_Server_IP = "8.8.8.8";
        int DNS_Server_Port = 53;
        var endpoint = new IPEndPoint(IPAddress.Parse(DNS_Server_IP), DNS_Server_Port);

        var client = new LookupClient(new LookupClientOptions(endpoint)
        {
            UseCache = false,
            EnableAuditTrail = false,
            Retries = 3,
            Timeout = TimeSpan.FromSeconds(10),
            ThrowDnsErrors = true                   
        });
        
        string Domain_Input = "google.com";
        
        Console.WriteLine("A Records for " + Domain_Input);
        Console.WriteLine("\n");
        
        foreach (var aRecord in client.Query(Domain_Input, QueryType.A).Answers.ARecords())
        {
            Console.WriteLine(aRecord.Address);
        } 
        
        Console.WriteLine("\n");
        Console.WriteLine("AAAA Records for " + Domain_Input);
        Console.WriteLine("\n");
          
        foreach (var AAAARecord in client.Query(Domain_Input, QueryType.AAAA).Answers.AaaaRecords())
        {
            Console.WriteLine(AAAARecord.Address);
        } 

        Console.WriteLine("\n");
        Console.WriteLine("MX Records for " + Domain_Input);
        Console.WriteLine("\n");

        foreach (var MxRecord1 in client.Query(Domain_Input, QueryType.MX).Answers.MxRecords())
        {
            Console.WriteLine(MxRecord1);
        } `

The plan was to do this for each relevant record needed. Just to let you know I am new to this so if I have raised this in the wrong place just say. Lastly, I have found your project very useful so thanks for that. 

The output is below:
A Records for google.com

216.58.212.206

AAAA Records for google.com

2a00:1450:4009:80b::200e

MX Records for google.com

google.com. 296 IN MX 40 alt3.aspmx.l.google.com.
google.com. 296 IN MX 50 alt4.aspmx.l.google.com.
google.com. 296 IN MX 30 alt2.aspmx.l.google.com.
google.com. 296 IN MX 20 alt1.aspmx.l.google.com.
google.com. 296 IN MX 10 aspmx.l.google.com.

Any help will be appreciated.

**Comment by MichaCo** [comment]
Stackoverflow is a better place for plain questions. This is more for bugs and issues you might have ;)

But anyways, there is nothing wrong with the results. How many answers you get from certain public DNS servers for the same domain will vary by a lot depending on the tides and where the sun is on that day. 
Kidding, but you can generally not rely on always getting the same response. 
The responses heavily depend on caching and which resolver was used and what you ask for exactly.
