### ISSUE TITLE
Specify the nameserver by hostname instead of IP address

### ISSUE THREAD

**Issue by ygoe** [MichaCo/DnsClient.NET#96]
I have a list of secondary nameservers for my domains. These are the names that are published in the domain's NS records. Now I need to query those nameservers directly to ensure that a new record was fully propagated to all secondaries. (This is a prerequisite of using the DNS challenge of the ACME protocol to generate an SSL certificate.)

The DNS LookupClient only lets me specify nameservers to query with their IP address. Do I have to start a separate query for the nameserver's name to find any of its addresses before I can query that server? Or have I missed something easy? Like usually, network clients accept a host name or IP address if they should connect to somewhere.

**Comment by MichaCo** [comment]
Yes, you have to do the first hop lookup yourself.

**Comment by ygoe** [comment]
Thanks for the response. If it's interesting for the project, I'd appreciate additional overloads that do that first lookup. It would be easier to call the methods and cause less clutter that isn't part of the actual lookup that the application is really interested in.

**Comment by MichaCo** [comment]
@ygoe that's not really in scope for this library. DNS lookups and DNS staleness would depend on how long the DnsClient instance is kept alive. Then I'd have to re-query after the TTL to eventually get a new IP address etc... 
Depending on the use case you might have to write a bit code or just a one liner.
