### ISSUE TITLE
ThrowDnsErrors Not Respected

### ISSUE THREAD

**Issue by MattInternet** [MichaCo/DnsClient.NET#99]
Currently no matter how I configure `LookupClientOptions`, including with `ThrowDnsErrors` set to false, the `LookoutClient` throws `DnsResponseException`s when it times out.

**Comment by MichaCo** [comment]
The ThrowDnsErrors flag only affects actual DNS responses, if the DNS response of the server is marked as having an error, like, bad request, or non-existent domain.

A connection timeout is completely different thing and client related and the library will and cannot ignore such errors.
You can check the exception, in a case of a timeout it should have `DnsResponseCode.ConnectionTimeout` set.

**Comment by MattInternet** [comment]
That makes total sense, thank you!
